# Generated by Django 5.2.8 on 2025-12-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parentprofile_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=500)),
                ('school_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacherprofile')),
            ],
        ),
    ]
