# Generated by Django 5.2.8 on 2025-12-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=150)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolprofile')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacherprofile')),
            ],
        ),
    ]
