# Generated by Django 5.2.8 on 2025-12-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_message_receiver_id_alter_message_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_body',
            field=models.TextField(default=None, null=True),
        ),
    ]
