# Generated by Django 5.2.8 on 2025-12-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.classroom')),
            ],
        ),
    ]
