# Generated by Django 5.2.8 on 2025-12-16 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_classroom_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolprofile'),
        ),
    ]
