# Generated by Django 5.2.8 on 2026-03-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_classroom_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_admin',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='burser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='institution_type',
            field=models.CharField(default='primary', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='core.schoolprofile'),
        ),
        migrations.DeleteModel(
            name='ParentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
