# Generated by Django 5.2.8 on 2026-03-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_teacherprofile_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='location',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
