# Generated by Django 5.2.8 on 2026-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_schoolprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_burser',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_principal',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
