# Generated by Django 5.2.8 on 2026-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customuser_is_burser_customuser_is_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
