# Generated by Django 5.2.8 on 2026-04-15 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(db_index=True, max_length=500, unique=True)),
                ('institution_type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=350, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('burser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burser', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='core.institution'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_staff', to='core.institution')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
