# Generated by Django 5.2.8 on 2026-04-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='institution_id',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
