# Generated by Django 5.2.8 on 2026-04-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_institution_id_staff_institution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('teacher', 'institution'), name='unique_staff_per_institution'),
        ),
    ]
