# Generated by Django 5.2.8 on 2026-04-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_school_id_classroom_school_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
