# Generated by Django 5.2.8 on 2026-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='school',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classroom_id',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='classroom',
            name='academic_session',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
