# Generated by Django 5.2.8 on 2026-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_student_date_of_birth_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=8, null=True),
        ),
    ]
