# Generated by Django 5.2.8 on 2026-05-12 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_conversation_uid_alter_classroom_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
