# Generated by Django 5.2.8 on 2026-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_conversation_participants_conversation_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='teacher',
        ),
    ]
