# Generated by Django 5.2.8 on 2026-05-21 05:10

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_message_file_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.MediaStorage(), upload_to='chat_files/'),
        ),
    ]
