# Generated by Django 5.2.8 on 2026-05-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_message_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
