# Generated by Django 5.2.8 on 2026-05-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
